# Generated by Django 4.0.3 on 2022-04-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entegrables',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
