# Generated by Django 4.0.3 on 2022-04-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_delete_entegrables_delete_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
