# Generated by Django 4.0.3 on 2022-04-11 01:33

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_estudiantes_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
