# Generated by Django 4.0.3 on 2022-04-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0004_post_delete_estudiantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
